name: "Build and test on Windows"
description: "Build and test package on Windows"
inputs:
  python-version:
    description: "Python version"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      name: Set up conda
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: testenv
        channels: conda-forge,defaults
        channel-priority: true
        python-version: ${{ inputs.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        conda install -c conda-forge -y "matplotlib>=3.3.2" "seaborn>=0.11.0" "tsfresh>=0.17.0" "hcrystalball>=0.1.9" "stumpy>=1.5.1" "fbprophet>=0.7.1" "numba>=0.50,<0.53" "numpy>=1.19" "pandas>=1.1.0,<1.2" "statsmodels>=0.12.1" "scikit-learn>=0.23.0" "scikit-posthocs>=0.6.5" "pystan>=2.14,<3.0"
        pip install -r build_tools/requirements.txt
        conda list
    - name: Build wheel
      run: |
        python setup.py build_ext --compiler=msvc
        python setup.py bdist_wheel bdist_wininst
        ls dist
    - uses: actions/install
    - uses: actions/test
