name: "Upload package to PyPI"
description: "Upload package to PyPI"
inputs:
  pypi-username:
    description: "PyPI username"
    required: true
  pypip-password:
    description: "PyPI password"
    required: true
runs:
  using: "composite"
  steps:
    - name: Upload wheel and source code tarball to PyPI
      env:
        TWINE_USERNAME: ${{ inputs.pypi-username }}
        TWINE_PASSWORD: ${{ inputs.pypi-password }}
      run: |
        ls -l dist/*
        python -m pip install --upgrade twine
        python -m twine upload -r pypi --non-interactive --skip-existing --verbose dist/*
